project_id = "bdfvhyfusrjgbgxrcyga"

[functions.submit-team-registration]
verify_jwt = false

[functions.list-team-names]
verify_jwt = false

[functions.admin-registrations]
verify_jwt = false

[functions.track-visitor]
verify_jwt = false

[functions.get-visitor-stats]
verify_jwt = false
